Feature/phrasing updates
eea-oasis/baseline-standard pull request #183
Opened 2022-09-06 16:38 UTC by Ybittan

Updated several requirements to improve phrasing, grammar, or missing content.

2022-09-06 17:18 UTC, Therecanbeonlyone1969 requested changes
See requested changes

2022-09-06 17:18 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +*For example, a Payment Term such as N30, a discount value, agreed upon product numbers, SLAs etc.*
```suggestion
*For example, a Payment Term such as N30, a discount value, agreed upon product numbers, Service Level Agreements (SLAs) etc.*
```

2022-09-06 17:18 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +The transacting counterparties MUST agree on which BPI to be used.
```suggestion
The transacting counterparties MUST agree on which BPI is to be used.
```

2022-09-06 17:18 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +*Example of this could be a JSON object with a response e.g. 200 or 403*
```suggestion
*Example of this could be a JSON object with a response e.g. the standard HTTP response 200 or 403*
```

2022-09-06 17:31 UTC, Therecanbeonlyone1969 approved these changes
LGTM now

2022-09-07 15:06 UTC, kthomas approved these changes

2022-09-07 15:07 UTC, merged