Testability statements for Section 5.1: BPI Subject Capabilities
eea-oasis/baseline-standard pull request #211
Opened 2023-06-20 23:22 UTC by Therecanbeonlyone1969

2023-06-26 22:17 UTC, Kasshern reviewed
@Therecanbeonlyone1969  Looks good overall left some comments - mostly spelling and grammar, some suggestions of repeat steps and possibly one or two confusing wordings. Will approve after response.

2023-06-26 22:17 UTC, Kasshern commented on core/baseline-core-v1.0-psd01.md
> +    * The internal BPI Subject can create a new BPI components.
component

2023-06-27 17:17 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +9. Perform encryption and decryption operations using different cryptographic algorithms supported by the BPI.
no. that is up to the implementer @Kasshern

2023-06-27 17:21 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +* Ensure that BPI Subjects have access to the necessary cryptographic functions for threshold digital signature creation and verification.
no. not required

2023-06-27 17:22 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +* Establish a digital signature threshold condition.
yes. you need to specify what the number of shares are to reconstitute ahead of time

2023-06-27 17:26 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +    * The internal BPI Subject can create a new BPI components.
done

2023-06-27 17:27 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +9. Utilize different cryptographic algorithms supported by the BPI for threshold digital signature creation.
agreed and corrected

2023-06-27 17:27 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +1. BPI Subject generates a key pair for digital signature using the BPI Subject.
corrected

2023-06-27 17:28 UTC, Therecanbeonlyone1969 commented on core/baseline-core-v1.0-psd01.md
> +* Set up a BPI yesy system with the necessary cryptographic algorithms and protocols.
yes

2023-09-26 16:13 UTC, Ybittan requested changes

2023-10-26 14:25 UTC, Ybittan approved these changes
LGTM

2023-10-26 14:30 UTC, Kasshern approved these changes

2023-10-26 14:36 UTC, merged