Adding Testability Statement to section 5.2: BPI Subject Account
eea-oasis/baseline-standard pull request #212
Opened 2023-06-22 23:33 UTC by Therecanbeonlyone1969

2023-06-26 21:31 UTC, Ybittan requested changes

2023-06-26 21:31 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +8. Verify that a BPI Subject Acount is not created and an appropriate error message is displayed.
```suggestion
8. Verify that a BPI Subject Account is not created and an appropriate error message is displayed.
```

2023-06-26 21:31 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* A cryptographic technique to ensure the cryptographic verifiablity of the audit trail.
```suggestion
* A cryptographic technique to ensure the cryptographic verifiability of the audit trail.
```

2023-06-26 21:31 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +1. Authenticate the internal BPI Subject aginst one of the BPI Subject Accounts for which the internal BPI Subject is authorized based on an existing security policy in said BPI Subject Account.
```suggestion
1. Authenticate the internal BPI Subject against one of the BPI Subject Accounts for which the internal BPI Subject is authorized based on an existing security policy in said BPI Subject Account.
```

2023-06-26 21:31 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* An existing BPI Subject Account exists and can be retrieved by an internal BPI Subject with the correct authorization based on an existin security policy.
```suggestion
* An existing BPI Subject Account exists and can be retrieved by an internal BPI Subject with the correct authorization based on an existing security policy.
```

2023-09-28 14:06 UTC, Ybittan approved these changes
LGTM

2023-10-26 14:31 UTC, Kasshern approved these changes

2023-10-26 14:35 UTC, merged