Testability Statements Section 5.3: BPI Service Orchestration
eea-oasis/baseline-standard pull request #213
Opened 2023-06-26 23:31 UTC by Therecanbeonlyone1969

2023-09-26 16:18 UTC, Ybittan requested changes

2023-09-26 16:18 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +7. Verify that BPI service orchestration failure is discvered and thet its built-in redundancies are successfully executed.
```suggestion
7. Verify that BPI service orchestration failure is discovered and that its built-in redundancies are successfully executed. 
```

2023-09-26 16:18 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +2. Only the invoking subscriber receives the expected responses or notifications from the BPI service invocation..
```suggestion
2. Only the invoking subscriber receives the expected responses or notifications from the BPI service invocation.
```

2023-09-26 16:18 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* The test is considered passed if the measured time for the BPI service request to propagate through the BPI serviceorchestration component and reach the BPI service consumer is below the defined "M
```suggestion
* The test is considered passed if the measured time for the BPI service request to propagate through the BPI service orchestration component and reach the BPI service consumer is below the defined "Material Impact" threshold.
```

2023-10-26 14:31 UTC, Kasshern approved these changes

2023-10-26 14:36 UTC, merged