Adding testability criteria for section 5.5.1 - 5.5.3
eea-oasis/baseline-standard pull request #215
Opened 2023-08-24 22:47 UTC by Therecanbeonlyone1969

2023-09-26 16:28 UTC, Ybittan requested changes

2023-09-26 16:28 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* The BPI accurately validates the BPI Subject's identity through the the authentication flow.
```suggestion
* The BPI accurately validates the BPI Subject's identity through the authentication flow. 
```

2023-09-26 16:28 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +8. Check if the cryptographic prover system and its specification are accurately listed.
```suggestion
8. Check if the cryptographic prover system and its specifications are accurately listed.
```

2023-09-26 16:28 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* The cryptographic prover system and its specification are correctly listed.
```suggestion
* The cryptographic prover system and its specifications are correctly listed.
```

2023-10-26 14:33 UTC, Kasshern approved these changes

2023-10-26 14:33 UTC, Ybittan approved these changes
LGTM

2023-10-26 14:33 UTC, merged