Testability Statements 5.5.4, 5.5.4,1, and 5.6 and 5.7
eea-oasis/baseline-standard pull request #216
Opened 2023-08-29 21:57 UTC by Therecanbeonlyone1969

Also made some minor clarifying edits to some requirements.

2023-08-29 21:59 UTC, Therecanbeonlyone1969 commented
The next PR will be for 5.5.4.2 which contains a lot of requirements, about 70. However, the requirements are very similar in structure and therefore the testability statements will be very similar.

2023-09-26 16:05 UTC, Ybittan requested changes
Other than a few minor grammatical suggestions, LGTM.

2023-09-26 16:05 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* A non-interactive zero-knowledge proof of a state object utilized in one or more mono-directional and/or bi-/multi-directional BPI Service from a prover system that can generate a zero-knowledge pr
```suggestion
* A non-interactive zero-knowledge proof of a state object utilized in one or more mono-directional and/or bi-/multi-directional BPI Services from a prover system that can generate a zero-knowledge proof of correctness for the output of size N. The size N is given by the size of the circuit used to generate the proof in terms of the number of circuit constraint equations.
```

2023-09-26 16:05 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +* The test will pass if the non-interactive zero-knowledge proof of a state object utilized in one or more mono-directional and/or bi-/multi-directional BPI Service can be verified by the verifier sy
```suggestion
* The test will pass if the non-interactive zero-knowledge proof of a state object utilized in one or more mono-directional and/or bi-/multi-directional BPI Services can be verified by the verifier system in a number of computational steps at most proportional to the size of the prover system that generated the proof.
```

2023-09-26 16:05 UTC, Ybittan commented on core/baseline-core-v1.0-psd01.md
> +1. The test system initiates a communication between two BPIs (source and target).
```suggestion
1. The test system initiates communication between two BPIs (source and target).
```

2023-10-26 14:34 UTC, Kasshern approved these changes

2023-10-26 14:35 UTC, merged