Update README.md
eea-oasis/baseline-standard pull request #82
Opened 2021-10-09 21:16 UTC by samratkishor

Added the present status.

2021-10-12 19:13 UTC, Therecanbeonlyone1969 requested changes
has not yet been submitted <- please change accordingly @samratkishor

2021-11-04 14:26 UTC, humbitious approved these changes

2021-11-04 14:27 UTC, morpheusdataio approved these changes

2021-11-04 14:27 UTC, Therecanbeonlyone1969 approved these changes

2021-11-04 14:28 UTC, merged